{% set name = "prr" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/danobi/prr/archive/v{{ version }}.tar.gz
  sha256: 3c32911854a33a1a7870382db0e759923315ec943b5d43dec42d751820473094

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl

test:
  commands:
    - prr --help

about:
  home: https://github.com/danobi/prr
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Mailing list style code reviews for github
  dev_url: https://github.com/danobi/prr

extra:
  recipe-maintainers:
    - danielnachun
